version: '2.3'
services:
  els-kibana:
    build:
      context: .
      target: base
    command: bash develop.sh
    environment:
      PYTHONPATH: .
    ports:
      - '9200:9200' # elastic
      - '5601:5601' # kibana
      - '8000:8000' # flask
      - '9000:9000' # supervisor


# docker-compose -f docker-compose.yml up --build      