version: '3.5'

services:

    consul:
        image: consul:latest
        restart: always
        ports:
          - 8500
        dns:
          - 127.0.0.1
        command: agent -server -client=0.0.0.0 -bootstrap -ui


    # kong:
    #     image: lieder-kong:0.9
    #     build:
    #         context: ./kong

    #     environment:
    #         # KONG_ADMIN_ACCESS_LOG: /dev/stdout
    #         # KONG_ADMIN_ERROR_LOG: /dev/stderr
    #         KONG_ADMIN_LISTEN: '0.0.0.0:8001'
    #         # KONG_CASSANDRA_CONTACT_POINTS: kong-database
    #         # KONG_DATABASE: postgres
    #         # KONG_PG_DATABASE: ${KONG_PG_DATABASE:-kong}
    #         # KONG_PG_HOST: kong-database
    #         # KONG_PG_USER: ${KONG_PG_USER:-kong}
    #         # KONG_PROXY_ACCESS_LOG: /dev/stdout
    #         # KONG_PROXY_ERROR_LOG: /dev/stderr
    #         # KONG_PG_PASSWORD: kong
    #     ports:
    #         - "8000:8000/tcp"
    #         - "127.0.0.1:8001:8001/tcp"
    #         - "8443:8443/tcp"
    #         - "127.0.0.1:8444:8444/tcp"
    #     deploy:
    #       mode: global
    #       restart_policy:
    #         condition: on-failure
    #       update_config:
    #         parallelism: 1
    #         failure_action: rollback
    #         delay: 15s


