version: '3.7'

services:
    kong:
        build:
            context: kong/
        container_name: kong_nodb
        volumes:
            - ./kong/config/kong.yml:/usr/local/kong/declarative/kong.yml:ro
        ports:
            - "8000:8000/tcp"
            - "127.0.0.1:8001:8001"
            - "8443:8443/tcp"
            - "127.0.0.1:8444:8444"
        environment:
            KONG_DATABASE: "off" # saying to kong that we will not use a database
            KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong.yml  # which declarative config we want to use and where is it.
            # KONG_PROXY_ACCESS_LOG: /dev/stdout
            # KONG_ADMIN_ACCESS_LOG: /dev/stdout
            # KONG_PROXY_ERROR_LOG: dev/stderr
            # KONG_ADMIN_ERROR_LOG: dev/stderr
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
            
        healthcheck:
            test: ["CMD", "kong", "health"]
            # test: ["CMD", "curl", "-f", "http://kong:8000"]
            interval: 10s
            timeout: 10s
            retries: 10
        restart: on-failure
        networks:
            - kong-net
            
    # web1: NGINX webserver that serves a simple page containing its hostname, IP address and port ...             
    web1:
        image: nginxdemos/hello:latest
        container_name: web1
        ports:
            - "9091:80"    
        networks:
            - kong-net

networks:
 kong-net:
    driver: bridge



 
 