# Use postgres/example user/password credentials
version: '3.6'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres:/var/lib/postgresql
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 28080:8080

# networks:
#   default:
#     name: dev
#     external: true

volumes:
  postgres:
